### PR TITLE
Linux support

### PR DESCRIPTION
**Pull request by HendrikMennen**
### What does this pull request do?
Add linux support

### How?
I changed the target to .netstandard2.0 and made restarting work on linux aswell.
This included copying a runtimeconfig.json to the storagefolder and using a different method to starting the dlls on linux.

### Todo
Dummy test is not working for some reason
Also I did only test on one linux distribution (Linux Mint)

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Thanks, I will look into it when I have more time. Can you please fix the conflicts meanwhile?

**Comment by HendrikMennen** [comment]
I don't know why the dummy test is failing. It opens the updater and for some reson doesn't get write access and waits forever. In my application it does work after exiting with Environment.Exit(0)

**Comment by Tyrrrz** [comment]
Question: Why do you need runtimeconfig.json, isn't it possible to specify `netcoreapp` target on Onova.Updater instead?

**Comment by HendrikMennen** [comment]
I don't know if there is a different way. Without it I get
> The library hostpolicy.dll was not found

I was not able to find a different solution

**Comment by Tyrrrz** [comment]
Sorry for silence, I'm preoccupied with other things, I'll get back to this later

**Comment by Tyrrrz** [comment]
Thank you for your contribution.
I came back to it and decided this was out of scope for now because I personally don't have any projects running on Linux that could use Onova, so it would be difficult for me to take ownership of something I can't really validate.
I will revisit this when .NET Core 3.0 is released and hopefully that will make the crossplatform direction more straightforward.

**Pull request closed without merging**
