### PR TITLE
Allow relative urls in manifest in WebPackageResolver

### PR DESCRIPTION
**Pull request by pipe01**
If there's a line like `1.2.3 ./build.zip` in `http://www.example.com/manifest.txt`, the archive URL will be set to `http://www.example.com/build.zip`.

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Hi. Nice improvement, this is actually really useful.
Maybe you can use `Uri` and use it's `Relative` tag to do this with even less additional code?

**Comment by pipe01** [comment]
Is that what you mean?

**Comment by Tyrrrz** [comment]
I meant more as:

1. Convert `_manifestUrl` to `Uri` and store in a var
2. Parse the package URL and create a *relative* URI based on the manifest URI. This will take care of all sorts of relative URLs automatically.

**Comment by pipe01** [comment]
That's basically what I'm doing, but without the intermediate variable.

**Comment by Tyrrrz** [comment]
Not exactly, since you wouldn't need to call `StartsWith` and bother with relative paths. 😛

**Pull request merged**
